### PR TITLE
Add <input /> to allow user to set number of questions

### PR DESCRIPTION
**Pull request by tfsjohan**
## PR Type
- [ ] Adding new question(s)
> **Warning**: We do not support the inclusion of questions directly copied from official GitHub certification exams. Please only submit original questions and content that you have created.`
- [ ] Other content changes (updating questions, answers, explanations or study resources)
- [x] Code changes (non-content)
- [ ] Documentation changes
- [ ] Other

## What's new?
Adds an <input type="number" /> element to allow the user to set the number of questions to include in practice round. Defaults to the number of available questions.

## Related issue(s)
Closes: #144  

## Screenshots
image

### CODE REVIEW

**Comment by FidelusAleksander** [comment]
This is great @tfsjohan ! :rocket: 

Let's remove the first line from the test card so the question count is not duplicated + bolded

**Comment by tfsjohan** [comment]
Done.

**Comment by FidelusAleksander** [comment]
Remove this bit aswell
```
.content .check-list li:first-child {
  font-weight: 600;
}
```

image

**Review by FidelusAleksander — APPROVED** [review]
Thanks @tfsjohan for all the work!

I'll get this merged :rocket:

**Comment by tfsjohan** [comment]
Thanks! Happy to contribute! I'll use this myself a lot when practicing for Advanced Security.

**Comment by FidelusAleksander** [comment]
@tfsjohan I'm taking that exam on friday aswell! Good luck!

p.s thinking if i should enable discussions on this repository for people to ask questions/study together

**Comment by tfsjohan** [comment]
Yeah why not! I think that might be a good idea. I would for sure would have liked something like that before I took the first exam. 

That's probably a better place for those kind of questions than using issues. And also it might be a good way to use what's asked about in the exam for real.

**Comment by FidelusAleksander** [comment]
Never really used GitHub Discussions too much, but i've set something up right now :) Talk to you there! @tfsjohan

**Pull request merged**
